# Generated by Django 4.2.23 on 2025-07-03 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='書名')),
                ('description', models.TextField(verbose_name='簡介')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='novel_covers/', verbose_name='封面圖片')),
                ('status', models.CharField(choices=[('ONGOING', '連載中'), ('COMPLETED', '已完結'), ('HIATUS', '休刊中')], default='ONGOING', max_length=50, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novels', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='章節標題')),
                ('content_path', models.CharField(max_length=255, verbose_name='內容檔案路徑')),
                ('order', models.PositiveIntegerField(verbose_name='章節順序')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='發布時間')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='core.novel', verbose_name='所屬小說')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('novel', 'order')},
            },
        ),
    ]
