# Generated by Django 4.2.23 on 2025-07-07 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_avatar_authorprofile_alter_novel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='content_path',
        ),
        migrations.AddField(
            model_name='chapter',
            name='content',
            field=models.TextField(null=True, verbose_name='內容'),
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_to_bookshelf_at', models.DateTimeField(auto_now_add=True, verbose_name='加入書架時間')),
                ('last_read_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.chapter')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progresses', to='core.novel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_to_bookshelf_at'],
                'unique_together': {('user', 'novel')},
            },
        ),
    ]
