# Generated by Django 4.2.23 on 2025-07-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_chapter_content_path_chapter_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.TextField(default='', verbose_name='內容'),
        ),
    ]
