# Generated by Django 4.2.23 on 2025-07-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_chapter_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='觀看次數'),
        ),
    ]
