# Generated by Django 4.2.23 on 2025-07-08 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_chapter_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='卷標題')),
                ('order', models.PositiveIntegerField(verbose_name='卷順序')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='core.novel', verbose_name='所屬小說')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('novel', 'order')},
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='volume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='core.volume', verbose_name='所屬卷'),
        ),
    ]
