# Generated by Django 4.2.23 on 2025-07-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_volume_chapter_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('PUBLISHED', '已發布')], default='DRAFT', max_length=10, verbose_name='狀態'),
        ),
    ]
