# Generated by Django 4.2.23 on 2025-07-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_chapter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='總觀看次數'),
        ),
    ]
