# Generated by Django 4.2.23 on 2025-07-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_novel_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='volume_covers/', verbose_name='卷封面'),
        ),
        migrations.AddField(
            model_name='volume',
            name='description',
            field=models.TextField(blank=True, verbose_name='簡介'),
        ),
    ]
