# Generated by Django 4.2.23 on 2025-12-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_volume_cover_image_volume_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='category',
            field=models.CharField(choices=[('FANTASY', '奇幻'), ('SCIFI', '科幻'), ('ROMANCE', '言情'), ('URBAN', '都市'), ('HISTORY', '歷史'), ('MARTIAL', '武俠'), ('OTHERS', '其他')], default='OTHERS', max_length=50, verbose_name='分類'),
        ),
    ]
