# Generated by Django 4.2.23 on 2025-12-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_novel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最後更新時間'),
        ),
    ]
